using Npgsql;

namespace Pino.BrowserTests;

internal sealed partial class BrowserSession
{
    private async Task CleanDatabaseAsync()
    {
        if (_emails.Count == 0) { return; }
        // Exact emails are generated by this session; no truncation, schema reset, or wildcard deletion.
        await using var connection = new NpgsqlConnection(Environment.GetEnvironmentVariable("PINO_TEST_DATABASE"));
        await connection.OpenAsync(CancellationToken.None);
        await using var transaction = await connection.BeginTransactionAsync(CancellationToken.None);
        const string Sql = """
            SELECT pg_advisory_xact_lock(731923981);
            CREATE TEMP TABLE owned_users ON COMMIT DROP AS SELECT "Id" FROM "AspNetUsers" WHERE "Email" = ANY(@emails);
            CREATE TEMP TABLE owned_clubs ON COMMIT DROP AS SELECT "Id" FROM "Clubs" WHERE "CreatedBy" IN (SELECT "Id" FROM owned_users);
            INSERT INTO "PhotoDeletions" ("PhotoKey", "NotBefore")
              SELECT "PhotoKey", NOW() FROM "ClubProfiles" WHERE "UserId" IN (SELECT "Id" FROM owned_users) AND "PhotoKey" IS NOT NULL
              UNION SELECT "PhotoKey", NOW() FROM "Players" WHERE "ClubId" IN (SELECT "Id" FROM owned_clubs) AND "PhotoKey" IS NOT NULL
              ON CONFLICT ("PhotoKey") DO UPDATE SET "NotBefore" = NOW();
            DELETE FROM "PlayerNotes" WHERE "ClubId" IN (SELECT "Id" FROM owned_clubs);
            DELETE FROM "EnrollmentChanges" WHERE "ClubId" IN (SELECT "Id" FROM owned_clubs);
            DELETE FROM "PlayerErasures" WHERE "ClubId" IN (SELECT "Id" FROM owned_clubs);
            DELETE FROM "PlayerImportReceipts" WHERE "ClubId" IN (SELECT "Id" FROM owned_clubs);
            DELETE FROM "SportingBatchReceipts" WHERE "ClubId" IN (SELECT "Id" FROM owned_clubs);
            DELETE FROM "TryoutTeamAvailabilities" WHERE "ClubId" IN (SELECT "Id" FROM owned_clubs);
            DELETE FROM "SeasonTeamAvailabilities" WHERE "ClubId" IN (SELECT "Id" FROM owned_clubs);
            DELETE FROM "TeamPositionTargets" WHERE "ClubId" IN (SELECT "Id" FROM owned_clubs);
            DELETE FROM "DecisionEvents" WHERE "ClubId" IN (SELECT "Id" FROM owned_clubs);
            DELETE FROM "TryoutCloseouts" WHERE "ClubId" IN (SELECT "Id" FROM owned_clubs);
            DELETE FROM "Participations" WHERE "ClubId" IN (SELECT "Id" FROM owned_clubs);
            DELETE FROM "SeasonPlacements" WHERE "ClubId" IN (SELECT "Id" FROM owned_clubs);
            DELETE FROM "Players" WHERE "ClubId" IN (SELECT "Id" FROM owned_clubs);
            DELETE FROM "SportTeams" WHERE "ClubId" IN (SELECT "Id" FROM owned_clubs);
            DELETE FROM "TryoutEvents" WHERE "ClubId" IN (SELECT "Id" FROM owned_clubs);
            DELETE FROM "Seasons" WHERE "ClubId" IN (SELECT "Id" FROM owned_clubs);
            DELETE FROM "ClubJoinRequests" WHERE "ClubId" IN (SELECT "Id" FROM owned_clubs) OR "UserId" IN (SELECT "Id" FROM owned_users);
            DELETE FROM "StaffEmails" WHERE "ClubId" IN (SELECT "Id" FROM owned_clubs) OR "RecipientEmail" = ANY(@emails);
            DELETE FROM "ClubInvitations" WHERE "ClubId" IN (SELECT "Id" FROM owned_clubs) OR "Email" = ANY(@emails);
            DELETE FROM "ClubMemberships" WHERE "ClubId" IN (SELECT "Id" FROM owned_clubs) OR "UserId" IN (SELECT "Id" FROM owned_users);
            DELETE FROM "Clubs" WHERE "Id" IN (SELECT "Id" FROM owned_clubs);
            DELETE FROM "AspNetUsers" WHERE "Id" IN (SELECT "Id" FROM owned_users);
            """;
        await using var command = new NpgsqlCommand(Sql, connection, transaction);
        command.Parameters.AddWithValue("emails", _emails.ToArray());
        await command.ExecuteNonQueryAsync(CancellationToken.None);
        await transaction.CommitAsync(CancellationToken.None);
    }
}
